language: perl
sudo: required
perl:
  - "5.12"
  - "5.14"
  - "5.16"
  - "5.18"
  - "5.20"
  - "5.22"
  - "5.24"
  - "5.26"

matrix:
  include:
    - perl: 5.12
      env: MOJO_PROCESS_DEBUG=1 MOJO_EVENTEMITTER_DEBUG=1

before_script:
  - cpanm --quiet --notest --skip-satisfied Devel::Cover Devel::Cover::Report::Codecov
  - sudo ./tools/setup "$USER"

script:
  - perl Build.PL
  - ./Build build
  - cover -test

after_success:
  - cover -report codecov
